ssh linprog1 'pkill -u chetty'
ssh linprog2 'pkill -u chetty'
ssh linprog3 'pkill -u chetty'
ssh linprog4 'pkill -u chetty'
ssh program1 'pkill -u chetty'
ssh program2 'pkill -u chetty'
ssh program3 'pkill -u chetty'
ssh program4 'pkill -u chetty'
ssh shell 'pkill -u chetty'

