first : second third fourth
	echo first > /dev/null
second : fifth sixth
	echo second > /dev/null
third : 
	echo third > /dev/null
fourth:
	echo fourth > /dev/null
fifth:
	echo fifth > /dev/null
sixth:
	echo $@ > /dev/null

